---
- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask
  tasks:
    - debug:
        msg: "Start Flask App setup"

    - name: Do Commond Tasks
      include_role:
        name: common
      vars:
        satellite_activationkey: gpte-labs-rhel8
        satellite_org: prod

    #- name: Setup firewall
    #  include_role:
    #    name: firewall
    #  vars:
    #    firewall_services:
    #      - http
    #    firewall_tcp_ports:
    #      - 8080

    - name: Setup  Flask APP
      include_role:
        name: install_flask

    - debug:
        msg: "Finished Flask App setup"
