---
- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: true
  tags:
    - database_servers
  #vars:
  vars_files:
    - vars/postgre_vars.yml
  tasks:
    - name: Do Commond Tasks
      include_role:
        name: common
      vars:
        satellite_activationkey: gpte-labs-rhel8
        satellite_org: prod

    - name: Setup firewall
      include_role:
        name: firewall
      vars:
        firewall_services:
          - postgresql
        firewall_tcp_ports:
        - 5432

    - name: Install and Initialize Postgre12
      include_role:
        name: geerlingguy_edited.postgresql12
