- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tags:
    - smoketest

  tasks:

    - name: Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "{{ groups.database_servers[0] }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

- name: End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: false
  tags:
    - smoketest
  tasks:

    - name: Check webserver for correct response
      uri:
        url: "http://{{ hostvars[item].ansible_host }}:8080/"
        #url: "http://{{ hostvars[item].ansible_host }}/ping"
        #url: "http://frontend1/ping"
        return_content: yes
      until: '"Ansible Automation Platform" in result.content'
      retries: 10
      delay: 1
      register: result
      loop: "{{ lookup('items', groups['load_balancers'][0], wantlist=True) }}"
      delegate_to: localhost
